treewide: Add void argument to old-style zero prototype functions
Newer clang builds complain about old-style function declarations
not having any prototype assigned. The missing arguments are
triggering the Wstrict-prototype warns. Explicitly add the
`void` argument to satisfy the compiler.

This fixes the following warnings:

../drivers/video/fbdev/msm/mdss_mdp.c:4871:32: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct irq_info *mdss_intr_line()
                               ^
                                void

../drivers/video/fbdev/msm/mdss_util.c:226:42: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct mdss_util_intf *mdss_get_util_intf()
                                         ^
                                          void